name: Generate keymap image
on:
  push:
    branches: ["main"]
jobs:
  build-json:
    runs-on: ubuntu-latest
    container:
      image: qmkfm/qmk_cli:latest
      options: --entrypoint=sh --user root

    steps:
      - uses: actions/checkout@v4
      - run: mkdir -p qmk
      - uses: actions/checkout@v4
        name: Clone QMK firmware 
        with:
          repository: qmk/qmk_firmware
          submodules: recursive
          path: qmk
      - name: Symlink keyboard
        id: symlink-keyboard
        run: |
             mkdir -p output
             ls -R qmk
             cd qmk/qmk-firmware/keyboards/projectcain
             ln -s $GITHUB_WORKSPACE/vault35rp ./
             qmk c2json -km sherman -kb projectcain/vault35rp > $GITHUB_WORKSPACE/output/keymap.json
             cd $GITHUB_WORKSPACE
             cat $GITHUB_WORKSPACE/output/keymap.json
      - name: Cache QMK
        uses: actions/cache@v4
        id: cache-qmk
        with:
          path: qmk
          key: qmk
      - name: Cache JSON
        uses: actions/cache@v4
        id: cache-json
        with:
          path: output/keymap.json
          key: keymap
  #  build-svg:
  #    runs-on: ubuntu-latest
  #    container:
  #      image: ghcr.io/hnaderi/keymap-drawer:latest
  #      options: --entrypoint=sh
  #    steps:
  #      - uses: actions/checkout@v4
  #      - name: Restore JSON
  #        uses: actions/cache@v4
  #        id: restore-json
  #        with:
  #          path: output/keymap.json
  #          key: keymap
  #      - name: Restore QMK
  #        uses: actions/cache@v4
  #        id: restore-qmk
  #        with:
  #          path: qmk
  #          key: qmk
  #      - name: Create SVG file
  #        id: create-svg
  #        run: |
  #          keymap parse -c 4 -q output/keymap.json | keymap draw - -j vault35rp/info.json -l LAYOUT_wkl > output/keyboard.svg
  #      - uses: actions/upload-artifact@v4
  #        id: upload-svg
  #        with:
  #          name: output
  #          path: |
  #            vault35rp/output/*.svg
  #
