name: Generate keymap image
on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/hnaderi/keymap-drawer:latest
      options: --entrypoint=sh
    steps:
      - uses: actions/checkout@v4
      - name: Create SVG file
        id: create-svg
        run: |
          cd vault35rp
          make build
      - uses: actions/upload-artifact@v4
        id: upload-svg
        with:
          name: output
          path: |
            vault35rp/output/*.svg

