name: Generate keymap image
on:
  push:
    branches: ["main"]
jobs:
  build-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Clone vault35 firmware
      - run: mkdir -p qmk
        name: Create QMK directory
      - uses: actions/checkout@v4
        name: Clone QMK firmware 
        with:
          repository: qmk/qmk_firmware
          submodules: recursive
          path: qmk
      - name: Install build tools
        run: |
          pipx install keymap-drawer
          pipx install qmk
          qmk setup -H qmk --yes
      - name: Symlink keyboard
        id: symlink-keyboard
        run: |
          mkdir -p output
          cd qmk/keyboards/projectcain
          ln -s $GITHUB_WORKSPACE/vault35rp ./
          qmk c2json -km sherman -kb projectcain/vault35rp > $GITHUB_WORKSPACE/output/keymap.json
          cd $GITHUB_WORKSPACE
          cat $GITHUB_WORKSPACE/output/keymap.json
      - name: Create SVG
        id: create-svg
        run: |
          keymap parse -c 4 -q output/keymap.json | keymap draw - -j vault35rp/info.json -l LAYOUT_wkl > output/keyboard.svg
      - uses: actions/upload-artifact@v4
        name: Upload SVG
        id: upload-svg
        with:
          name: svg-output
          path: |
            output/*.svg
      - name: Compile firmware
        id: compile-firmware
        run: |
           cd $GITHUB_WORKSPACE/qmk
           make projectcain/vault35rp:sherman
           ls $GITHUB_WORKSPACE/qmk/
      - uses: actions/upload-artifact@v4
        name: Upload firmware
        id: upload-firmware
        with:
          name: firmware-output
          path: |
           $GITHUB_WORKSPACE/qmk/*.uf2
